print("Olá mundo!")
print("Digite o seu nome para que eu possa saber quem é meu mestre:")
nome = input("(>)")
print("Excelente!",nome,"você é o meu mestre!")
print("Agora informe sua idade para eu poder saber!")
idade = int(input("(>)"))
print("Ok, então o seu nome é",nome,"e você tem",idade,"anos, entendi.")
